#!/bin/bash
# Report Aggregator - Combines all agent reports into unified PR comment
# Usage: ./report-aggregator.sh <code_review_file> <security_scan_file> [test_coverage_file]
# Output: Combined markdown report to stdout

set -euo pipefail

CODE_REVIEW_FILE="${1:-}"
SECURITY_SCAN_FILE="${2:-}"
TEST_COVERAGE_FILE="${3:-}"
OUTPUT_FILE="${4:-/tmp/review-report-$(date +%s).md}"

echo "Aggregating review reports..." >&2

# Read reports
CODE_REVIEW=""
if [[ -f "$CODE_REVIEW_FILE" ]]; then
    CODE_REVIEW=$(cat "$CODE_REVIEW_FILE")
fi

SECURITY_SCAN=""
if [[ -f "$SECURITY_SCAN_FILE" ]]; then
    SECURITY_SCAN=$(cat "$SECURITY_SCAN_FILE")
fi

TEST_COVERAGE=""
if [[ -f "$TEST_COVERAGE_FILE" ]]; then
    TEST_COVERAGE=$(cat "$TEST_COVERAGE_FILE")
fi

# Count issues from reports
count_pattern() {
    local content="$1"
    local pattern="$2"
    echo "$content" | grep -c "$pattern" 2>/dev/null || echo "0"
}

CRITICAL_COUNT=0
WARNING_COUNT=0
SUGGESTION_COUNT=0

# Count from code review
if [[ -n "$CODE_REVIEW" ]]; then
    CRITICAL_COUNT=$((CRITICAL_COUNT + $(count_pattern "$CODE_REVIEW" "🔴")))
    WARNING_COUNT=$((WARNING_COUNT + $(count_pattern "$CODE_REVIEW" "🟡")))
    SUGGESTION_COUNT=$((SUGGESTION_COUNT + $(count_pattern "$CODE_REVIEW" "🟢")))
fi

# Count from security scan
if [[ -n "$SECURITY_SCAN" ]]; then
    CRITICAL_COUNT=$((CRITICAL_COUNT + $(count_pattern "$SECURITY_SCAN" "CRITICAL")))
    WARNING_COUNT=$((WARNING_COUNT + $(count_pattern "$SECURITY_SCAN" "WARNING")))
fi

# Determine overall verdict
if [[ $CRITICAL_COUNT -gt 0 ]]; then
    OVERALL_STATUS="🔴 **ACTION REQUIRED** - Critical issues found"
    VERDICT="REQUEST_CHANGES"
elif [[ $WARNING_COUNT -gt 0 ]]; then
    OVERALL_STATUS="🟡 **REVIEW NEEDED** - Warnings found"
    VERDICT="COMMENT"
else
    OVERALL_STATUS="✅ **LOOKS GOOD** - No blocking issues"
    VERDICT="APPROVE"
fi

# Build checks passed list
CHECKS_PASSED=0
CHECKS_TOTAL=0

add_check() {
    local passed="$1"
    local name="$2"
    ((CHECKS_TOTAL++)) || true
    if [[ "$passed" == "true" ]]; then
        ((CHECKS_PASSED++)) || true
        echo "- ✅ $name"
    else
        echo "- ❌ $name"
    fi
}

CHECKS_LIST=""
if [[ -n "$CODE_REVIEW" ]]; then
    CHECKS_LIST="$CHECKS_LIST
$(add_check "true" "Code Review")"
else
    CHECKS_LIST="$CHECKS_LIST
$(add_check "false" "Code Review (skipped)")"
fi

if [[ -n "$SECURITY_SCAN" ]]; then
    if echo "$SECURITY_SCAN" | grep -q "CRITICAL"; then
        CHECKS_LIST="$CHECKS_LIST
$(add_check "false" "Security Scan")"
    else
        CHECKS_LIST="$CHECKS_LIST
$(add_check "true" "Security Scan")"
    fi
else
    CHECKS_LIST="$CHECKS_LIST
$(add_check "false" "Security Scan (skipped)")"
fi

if [[ -n "$TEST_COVERAGE" ]]; then
    CHECKS_LIST="$CHECKS_LIST
$(add_check "true" "Test Coverage")"
fi

# Generate final report
cat > "$OUTPUT_FILE" << EOF
<!-- AI-REVIEW-BOT -->
# 🤖 AI Review Report

$OVERALL_STATUS

## Summary

| Metric | Count |
|--------|-------|
| 🔴 Critical | $CRITICAL_COUNT |
| 🟡 Warnings | $WARNING_COUNT |
| 🟢 Suggestions | $SUGGESTION_COUNT |
| ✅ Checks | $CHECKS_PASSED/$CHECKS_TOTAL passed |

## Checks
$CHECKS_LIST

---

$CODE_REVIEW

---

$SECURITY_SCAN

EOF

if [[ -n "$TEST_COVERAGE" ]]; then
    cat >> "$OUTPUT_FILE" << EOF

---

$TEST_COVERAGE

EOF
fi

cat >> "$OUTPUT_FILE" << EOF

---

<details>
<summary>📋 About this review</summary>

This review was generated by the multi-agent review suite:
- **Code Review**: Kilocode/Goose/CCR (fallback chain)
- **Security Scan**: Pattern matching + dependency audit
- **Test Coverage**: pytest-cov analysis (if available)

Verdict: **$VERDICT**

*Report generated at $(date -Iseconds)*
</details>
EOF

cat "$OUTPUT_FILE"
echo "" >&2
echo "Report aggregated. Verdict: $VERDICT" >&2
echo "Critical: $CRITICAL_COUNT, Warnings: $WARNING_COUNT, Suggestions: $SUGGESTION_COUNT" >&2
